# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

os: osx
osx_image: xcode8
language: objective-c
rvm:
  - 2.3.0
#cache: cocoapods
podfile: Example/Podfile
before_install:
  - sw_vers # Show osx versions
  - gem cleanup cocoapods
  - gem uninstall cocoapods
  - gem install cocoapods -v 1.2.1
  - gem install xcpretty
  - pod --version
#  - pod repo update MBProgressHUD # The Travis repo are TOO old?
  - pod install --project-directory=Example
script:
  - set -o pipefail && xcodebuild test -workspace Example/Pbind.xcworkspace -scheme Pbind-Example -destination 'platform=iOS Simulator,name=iPhone 6S,OS=10.0' | xcpretty 
  - pod lib lint
